# Generated by Django 3.2.7 on 2021-09-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('matricula', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
